In [105]:
import pandas as pd

## **Series**

In [106]:
data = [100, 101, 102, 103]
series = pd.Series(data, index=['w', 'x', 'y', 'z'])
print(series)

w    100
x    101
y    102
z    103
dtype: int64

In [107]:
print(series.loc['w'])
print(series.iloc[3])

100
103

In [108]:
series.iloc[3] = 110

In [109]:
print(series)

w    100
x    101
y    102
z    110
dtype: int64

In [110]:
## Filter Data

data = pd.Series([1,2,3,4,5,6,7,8,9])
print(data[data >=6])
print(data[data <=6])
print(data[data % 2 == 0])
print(data[data % 3 == 0])
print(data.min())
print(data.max())

5    6
6    7
7    8
8    9
dtype: int64
0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
1    2
3    4
5    6
7    8
dtype: int64
2    3
5    6
8    9
dtype: int64
1
9

In [111]:
calories = pd.Series({"Day 1": 420, "Day 2": 380, "Day 3": 390})
print(calories)
print(calories.loc["Day 1"])
print(calories.loc["Day 2"])
print(calories.loc["Day 3"])
print(calories.iloc[0])
print(calories.iloc[1])
print(calories.iloc[2])

Day 1    420
Day 2    380
Day 3    390
dtype: int64
420
380
390
420
380
390

In [112]:
calories.loc["Day 1"] = 500
print(calories)
calories.loc["Day 1"] += 500
print(calories)

Day 1    500
Day 2    380
Day 3    390
dtype: int64
Day 1    1000
Day 2     380
Day 3     390
dtype: int64

In [113]:
print(calories.loc["Day 1"])

1000

## **DataFrames**

In [114]:
data = {
    "Names" : ["Younus", "Yousaf", "Ali"],
    "Age" : [17, 19, 13],
    "Grade" : ["A+", "A", "B"]
}

df = pd.DataFrame(data, index = ["Student 1", "Student 2", "Student 3"])
df

            Names  Age Grade
Student 1  Younus   17    A+
Student 2  Yousaf   19     A
Student 3     Ali   13     B

In [115]:
df.loc["Student 1"]

Names    Younus
Age          17
Grade        A+
Name: Student 1, dtype: object

In [116]:
df.iloc[2]

Names    Ali
Age       13
Grade      B
Name: Student 3, dtype: object

In [117]:
df[df["Age"] == 13]

          Names  Age Grade
Student 3   Ali   13     B

In [118]:
df[df["Names"] == "Younus"]

            Names  Age Grade
Student 1  Younus   17    A+

In [119]:
df[(df["Age"] > 13) & (df["Grade"] == "A+")]

            Names  Age Grade
Student 1  Younus   17    A+

In [120]:
## Add a new colunm

df["City"] = ["Karachi", "Lahore", "Islamabad"]
df

            Names  Age Grade       City
Student 1  Younus   17    A+    Karachi
Student 2  Yousaf   19     A     Lahore
Student 3     Ali   13     B  Islamabad

In [121]:
## Add a new record

# Method - 1

new_student = {
    "Names":"Anees",
    "Age":17,
    "Grade":"A+",
    "City":"Karachi"
}

df.loc["Student 4"] = new_student

df

            Names  Age Grade       City
Student 1  Younus   17    A+    Karachi
Student 2  Yousaf   19     A     Lahore
Student 3     Ali   13     B  Islamabad
Student 4   Anees   17    A+    Karachi

In [122]:

# Method - 2

df.loc["Student 6"] = {
    "Names":"Shoaib",
    "Age":21,
    "Grade":"C",
    "City":"Karachi"
}

df

            Names  Age Grade       City
Student 1  Younus   17    A+    Karachi
Student 2  Yousaf   19     A     Lahore
Student 3     Ali   13     B  Islamabad
Student 4   Anees   17    A+    Karachi
Student 6  Shoaib   21     C    Karachi

In [123]:
# Method - 3 (Recommended / Official)
student_7 = pd.DataFrame([{"Names":"Awais", "Age":11, "Grade":"D", "City":"Lahore"}], index=["Student 7"])
df = pd.concat([df, student_7])
df

            Names  Age Grade       City
Student 1  Younus   17    A+    Karachi
Student 2  Yousaf   19     A     Lahore
Student 3     Ali   13     B  Islamabad
Student 4   Anees   17    A+    Karachi
Student 6  Shoaib   21     C    Karachi
Student 7   Awais   11     D     Lahore

## **Importing of files and Analysis on them**

In [126]:
df = pd.read_csv("/content/tips.csv")
df.head(5)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [180]:
df.shape # It returns the ordered pair of rows and colunms of dataset. (244, 8)
# Here: 244 = Rows, 8 = Colunms

(244, 8)

In [170]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
 7   final_bill  244 non-null    float64
dtypes: float64(3), int64(1), object(4)
memory usage: 15.4+ KB

In [184]:
df.describe()

       total_bill         tip        size  final_bill
count  244.000000  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672   22.784221
std      8.902412    1.383638    0.951100    9.890116
min      3.070000    1.000000    1.000000    4.070000
25%     13.347500    2.000000    2.000000   15.475000
50%     17.795000    2.900000    2.000000   20.600000
75%     24.127500    3.562500    3.000000   27.722500
max     50.810000   10.000000    6.000000   60.810000

In [127]:
final_bill = df["total_bill"] + df["tip"]
df["final_bill"] = pd.Series(final_bill)
df.head()

   total_bill   tip     sex smoker  day    time  size  final_bill
0       16.99  1.01  Female     No  Sun  Dinner     2       18.00
1       10.34  1.66    Male     No  Sun  Dinner     3       12.00
2       21.01  3.50    Male     No  Sun  Dinner     3       24.51
3       23.68  3.31    Male     No  Sun  Dinner     2       26.99
4       24.59  3.61  Female     No  Sun  Dinner     4       28.20

In [140]:
male_customers = df[(df['sex'] == 'Male') & (df['smoker'] == 'Yes') & (df['day'] == 'Sun') & (df['time'] == 'Dinner')]
male_customers["sex"].count()
male_customers

     total_bill   tip   sex smoker  day    time  size  final_bill
172        7.25  5.15  Male    Yes  Sun  Dinner     2       12.40
173       31.85  3.18  Male    Yes  Sun  Dinner     2       35.03
174       16.82  4.00  Male    Yes  Sun  Dinner     2       20.82
175       32.90  3.11  Male    Yes  Sun  Dinner     2       36.01
176       17.89  2.00  Male    Yes  Sun  Dinner     2       19.89
177       14.48  2.00  Male    Yes  Sun  Dinner     2       16.48
179       34.63  3.55  Male    Yes  Sun  Dinner     2       38.18
180       34.65  3.68  Male    Yes  Sun  Dinner     4       38.33
181       23.33  5.65  Male    Yes  Sun  Dinner     2       28.98
182       45.35  3.50  Male    Yes  Sun  Dinner     3       48.85
183       23.17  6.50  Male    Yes  Sun  Dinner     4       29.67
184       40.55  3.00  Male    Yes  Sun  Dinner     2       43.55
187       30.46  2.00  Male    Yes  Sun  Dinner     5       32.46
189       23.10  4.00  Male    Yes  Sun  Dinner     3       27.10
190       15.69  1.50  Male    Yes  Sun  Dinner     2       17.19

In [143]:
total_revenue = 0 # This is the revenue of just male_customers we found above
for revenue in male_customers["final_bill"]:
  total_revenue += revenue

total_revenue

444.94

In [150]:
new = df.to_string() # this way you can see whole data at once, but if we use .head(), so we will just see the first and last fives rows
print(new)

     total_bill    tip     sex smoker   day    time  size  final_bill
0         16.99   1.01  Female     No   Sun  Dinner     2       18.00
1         10.34   1.66    Male     No   Sun  Dinner     3       12.00
2         21.01   3.50    Male     No   Sun  Dinner     3       24.51
3         23.68   3.31    Male     No   Sun  Dinner     2       26.99
4         24.59   3.61  Female     No   Sun  Dinner     4       28.20
5         25.29   4.71    Male     No   Sun  Dinner     4       30.00
6          8.77   2.00    Male     No   Sun  Dinner     2       10.77
7         26.88   3.12    Male     No   Sun  Dinner     4       30.00
8         15.04   1.96    Male     No   Sun  Dinner     2       17.00
9         14.78   3.23    Male     No   Sun  Dinner     2       18.01
10        10.27   1.71    Male     No   Sun  Dinner     2       11.98
11        35.26   5.00  Female     No   Sun  Dinner     4       40.26
12        15.42   1.57    Male     No   Sun  Dinner     2       16.99
13        18.43   3.00    Male     No   Sun  Dinner     4       21.43
14        14.83   3.02  Female     No   Sun  Dinner     2       17.85
15        21.58   3.92    Male     No   Sun  Dinner     2       25.50
16        10.33   1.67  Female     No   Sun  Dinner     3       12.00
17        16.29   3.71    Male     No   Sun  Dinner     3       20.00
18        16.97   3.50  Female     No   Sun  Dinner     3       20.47
19        20.65   3.35    Male     No   Sat  Dinner     3       24.00
20        17.92   4.08    Male     No   Sat  Dinner     2       22.00
21        20.29   2.75  Female     No   Sat  Dinner     2       23.04
22        15.77   2.23  Female     No   Sat  Dinner     2       18.00
23        39.42   7.58    Male     No   Sat  Dinner     4       47.00
24        19.82   3.18    Male     No   Sat  Dinner     2       23.00
25        17.81   2.34    Male     No   Sat  Dinner     4       20.15
26        13.37   2.00    Male     No   Sat  Dinner     2       15.37
27        12.69   2.00    Male     No   Sat  Dinner     2       14.69
28        21.70   4.30    Male     No   Sat  Dinner     2       26.00
29        19.65   3.00  Female     No   Sat  Dinner     2       22.65
30         9.55   1.45    Male     No   Sat  Dinner     2       11.00
31        18.35   2.50    Male     No   Sat  Dinner     4       20.85
32        15.06   3.00  Female     No   Sat  Dinner     2       18.06
33        20.69   2.45  Female     No   Sat  Dinner     4       23.14
34        17.78   3.27    Male     No   Sat  Dinner     2       21.05
35        24.06   3.60    Male     No   Sat  Dinner     3       27.66
36        16.31   2.00    Male     No   Sat  Dinner     3       18.31
37        16.93   3.07  Female     No   Sat  Dinner     3       20.00
38        18.69   2.31    Male     No   Sat  Dinner     3       21.00
39        31.27   5.00    Male     No   Sat  Dinner     3       36.27
40        16.04   2.24    Male     No   Sat  Dinner     3       18.28
41        17.46   2.54    Male     No   Sun  Dinner     2       20.00
42        13.94   3.06    Male     No   Sun  Dinner     2       17.00
43         9.68   1.32    Male     No   Sun  Dinner     2       11.00
44        30.40   5.60    Male     No   Sun  Dinner     4       36.00
45        18.29   3.00    Male     No   Sun  Dinner     2       21.29
46        22.23   5.00    Male     No   Sun  Dinner     2       27.23
47        32.40   6.00    Male     No   Sun  Dinner     4       38.40
48        28.55   2.05    Male     No   Sun  Dinner     3       30.60
49        18.04   3.00    Male     No   Sun  Dinner     2       21.04
50        12.54   2.50    Male     No   Sun  Dinner     2       15.04
51        10.29   2.60  Female     No   Sun  Dinner     2       12.89
52        34.81   5.20  Female     No   Sun  Dinner     4       40.01
53         9.94   1.56    Male     No   Sun  Dinner     2       11.50
54        25.56   4.34    Male     No   Sun  Dinner     4       29.90
55        19.49   3.51    Male     No   Sun  Dinner     2       23.00
56        38.01   3.00    Male    Yes   Sat  Dinner     4       41.01
57        26.41   1.50  Female     No   Sat  Dinner     2       27.91
58        11.24   1.76    Male    Yes   Sat  Dinner     2       13.00
59        48.27   6.73    Male     No   Sat  Dinner     4       55.00
60        20.29   3.21    Male    Yes   Sat  Dinner     2       23.50
61        13.81   2.00    Male    Yes   Sat  Dinner     2       15.81
62        11.02   1.98    Male    Yes   Sat  Dinner     2       13.00
63        18.29   3.76    Male    Yes   Sat  Dinner     4       22.05
64        17.59   2.64    Male     No   Sat  Dinner     3       20.23
65        20.08   3.15    Male     No   Sat  Dinner     3       23.23
66        16.45   2.47  Female     No   Sat  Dinner     2       18.92
67         3.07   1.00  Female    Yes   Sat  Dinner     1        4.07
68        20.23   2.01    Male     No   Sat  Dinner     2       22.24
69        15.01   2.09    Male    Yes   Sat  Dinner     2       17.10
70        12.02   1.97    Male     No   Sat  Dinner     2       13.99
71        17.07   3.00  Female     No   Sat  Dinner     3       20.07
72        26.86   3.14  Female    Yes   Sat  Dinner     2       30.00
73        25.28   5.00  Female    Yes   Sat  Dinner     2       30.28
74        14.73   2.20  Female     No   Sat  Dinner     2       16.93
75        10.51   1.25    Male     No   Sat  Dinner     2       11.76
76        17.92   3.08    Male    Yes   Sat  Dinner     2       21.00
77        27.20   4.00    Male     No  Thur   Lunch     4       31.20
78        22.76   3.00    Male     No  Thur   Lunch     2       25.76
79        17.29   2.71    Male     No  Thur   Lunch     2       20.00
80        19.44   3.00    Male    Yes  Thur   Lunch     2       22.44
81        16.66   3.40    Male     No  Thur   Lunch     2       20.06
82        10.07   1.83  Female     No  Thur   Lunch     1       11.90
83        32.68   5.00    Male    Yes  Thur   Lunch     2       37.68
84        15.98   2.03    Male     No  Thur   Lunch     2       18.01
85        34.83   5.17  Female     No  Thur   Lunch     4       40.00
86        13.03   2.00    Male     No  Thur   Lunch     2       15.03
87        18.28   4.00    Male     No  Thur   Lunch     2       22.28
88        24.71   5.85    Male     No  Thur   Lunch     2       30.56
89        21.16   3.00    Male     No  Thur   Lunch     2       24.16
90        28.97   3.00    Male    Yes   Fri  Dinner     2       31.97
91        22.49   3.50    Male     No   Fri  Dinner     2       25.99
92         5.75   1.00  Female    Yes   Fri  Dinner     2        6.75
93        16.32   4.30  Female    Yes   Fri  Dinner     2       20.62
94        22.75   3.25  Female     No   Fri  Dinner     2       26.00
95        40.17   4.73    Male    Yes   Fri  Dinner     4       44.90
96        27.28   4.00    Male    Yes   Fri  Dinner     2       31.28
97        12.03   1.50    Male    Yes   Fri  Dinner     2       13.53
98        21.01   3.00    Male    Yes   Fri  Dinner     2       24.01
99        12.46   1.50    Male     No   Fri  Dinner     2       13.96
100       11.35   2.50  Female    Yes   Fri  Dinner     2       13.85
101       15.38   3.00  Female    Yes   Fri  Dinner     2       18.38
102       44.30   2.50  Female    Yes   Sat  Dinner     3       46.80
103       22.42   3.48  Female    Yes   Sat  Dinner     2       25.90
104       20.92   4.08  Female     No   Sat  Dinner     2       25.00
105       15.36   1.64    Male    Yes   Sat  Dinner     2       17.00
106       20.49   4.06    Male    Yes   Sat  Dinner     2       24.55
107       25.21   4.29    Male    Yes   Sat  Dinner     2       29.50
108       18.24   3.76    Male     No   Sat  Dinner     2       22.00
109       14.31   4.00  Female    Yes   Sat  Dinner     2       18.31
110       14.00   3.00    Male     No   Sat  Dinner     2       17.00
111        7.25   1.00  Female     No   Sat  Dinner     1        8.25
112       38.07   4.00    Male     No   Sun  Dinner     3       42.07
113       23.95   2.55    Male     No   Sun  Dinner     2       26.50
114       25.71   4.00  Female     No   Sun  Dinner     3       29.71
115       17.31   3.50  Female     No   Sun  Dinner     2       20.81
116       29.93   5.07    Male     No   Sun  Dinner     4       35.00
117       10.65   1.50  Female     No  Thur   Lunch     2       12.15
118       12.43   1.80  Female     No  Thur   Lunch     2       14.23
119       24.08   2.92  Female     No  Thur   Lunch     4       27.00
120       11.69   2.31    Male     No  Thur   Lunch     2       14.00
121       13.42   1.68  Female     No  Thur   Lunch     2       15.10
122       14.26   2.50    Male     No  Thur   Lunch     2       16.76
123       15.95   2.00    Male     No  Thur   Lunch     2       17.95
124       12.48   2.52  Female     No  Thur   Lunch     2       15.00
125       29.80   4.20  Female     No  Thur   Lunch     6       34.00
126        8.52   1.48    Male     No  Thur   Lunch     2       10.00
127       14.52   2.00  Female     No  Thur   Lunch     2       16.52
128       11.38   2.00  Female     No  Thur   Lunch     2       13.38
129       22.82   2.18    Male     No  Thur   Lunch     3       25.00
130       19.08   1.50    Male     No  Thur   Lunch     2       20.58
131       20.27   2.83  Female     No  Thur   Lunch     2       23.10
132       11.17   1.50  Female     No  Thur   Lunch     2       12.67
133       12.26   2.00  Female     No  Thur   Lunch     2       14.26
134       18.26   3.25  Female     No  Thur   Lunch     2       21.51
135        8.51   1.25  Female     No  Thur   Lunch     2        9.76
136       10.33   2.00  Female     No  Thur   Lunch     2       12.33
137       14.15   2.00  Female     No  Thur   Lunch     2       16.15
138       16.00   2.00    Male    Yes  Thur   Lunch     2       18.00
139       13.16   2.75  Female     No  Thur   Lunch     2       15.91
140       17.47   3.50  Female     No  Thur   Lunch     2       20.97
141       34.30   6.70    Male     No  Thur   Lunch     6       41.00
142       41.19   5.00    Male     No  Thur   Lunch     5       46.19
143       27.05   5.00  Female     No  Thur   Lunch     6       32.05
144       16.43   2.30  Female     No  Thur   Lunch     2       18.73
145        8.35   1.50  Female     No  Thur   Lunch     2        9.85
146       18.64   1.36  Female     No  Thur   Lunch     3       20.00
147       11.87   1.63  Female     No  Thur   Lunch     2       13.50
148        9.78   1.73    Male     No  Thur   Lunch     2       11.51
149        7.51   2.00    Male     No  Thur   Lunch     2        9.51
150       14.07   2.50    Male     No   Sun  Dinner     2       16.57
151       13.13   2.00    Male     No   Sun  Dinner     2       15.13
152       17.26   2.74    Male     No   Sun  Dinner     3       20.00
153       24.55   2.00    Male     No   Sun  Dinner     4       26.55
154       19.77   2.00    Male     No   Sun  Dinner     4       21.77
155       29.85   5.14  Female     No   Sun  Dinner     5       34.99
156       48.17   5.00    Male     No   Sun  Dinner     6       53.17
157       25.00   3.75  Female     No   Sun  Dinner     4       28.75
158       13.39   2.61  Female     No   Sun  Dinner     2       16.00
159       16.49   2.00    Male     No   Sun  Dinner     4       18.49
160       21.50   3.50    Male     No   Sun  Dinner     4       25.00
161       12.66   2.50    Male     No   Sun  Dinner     2       15.16
162       16.21   2.00  Female     No   Sun  Dinner     3       18.21
163       13.81   2.00    Male     No   Sun  Dinner     2       15.81
164       17.51   3.00  Female    Yes   Sun  Dinner     2       20.51
165       24.52   3.48    Male     No   Sun  Dinner     3       28.00
166       20.76   2.24    Male     No   Sun  Dinner     2       23.00
167       31.71   4.50    Male     No   Sun  Dinner     4       36.21
168       10.59   1.61  Female    Yes   Sat  Dinner     2       12.20
169       10.63   2.00  Female    Yes   Sat  Dinner     2       12.63
170       50.81  10.00    Male    Yes   Sat  Dinner     3       60.81
171       15.81   3.16    Male    Yes   Sat  Dinner     2       18.97
172        7.25   5.15    Male    Yes   Sun  Dinner     2       12.40
173       31.85   3.18    Male    Yes   Sun  Dinner     2       35.03
174       16.82   4.00    Male    Yes   Sun  Dinner     2       20.82
175       32.90   3.11    Male    Yes   Sun  Dinner     2       36.01
176       17.89   2.00    Male    Yes   Sun  Dinner     2       19.89
177       14.48   2.00    Male    Yes   Sun  Dinner     2       16.48
178        9.60   4.00  Female    Yes   Sun  Dinner     2       13.60
179       34.63   3.55    Male    Yes   Sun  Dinner     2       38.18
180       34.65   3.68    Male    Yes   Sun  Dinner     4       38.33
181       23.33   5.65    Male    Yes   Sun  Dinner     2       28.98
182       45.35   3.50    Male    Yes   Sun  Dinner     3       48.85
183       23.17   6.50    Male    Yes   Sun  Dinner     4       29.67
184       40.55   3.00    Male    Yes   Sun  Dinner     2       43.55
185       20.69   5.00    Male     No   Sun  Dinner     5       25.69
186       20.90   3.50  Female    Yes   Sun  Dinner     3       24.40
187       30.46   2.00    Male    Yes   Sun  Dinner     5       32.46
188       18.15   3.50  Female    Yes   Sun  Dinner     3       21.65
189       23.10   4.00    Male    Yes   Sun  Dinner     3       27.10
190       15.69   1.50    Male    Yes   Sun  Dinner     2       17.19
191       19.81   4.19  Female    Yes  Thur   Lunch     2       24.00
192       28.44   2.56    Male    Yes  Thur   Lunch     2       31.00
193       15.48   2.02    Male    Yes  Thur   Lunch     2       17.50
194       16.58   4.00    Male    Yes  Thur   Lunch     2       20.58
195        7.56   1.44    Male     No  Thur   Lunch     2        9.00
196       10.34   2.00    Male    Yes  Thur   Lunch     2       12.34
197       43.11   5.00  Female    Yes  Thur   Lunch     4       48.11
198       13.00   2.00  Female    Yes  Thur   Lunch     2       15.00
199       13.51   2.00    Male    Yes  Thur   Lunch     2       15.51
200       18.71   4.00    Male    Yes  Thur   Lunch     3       22.71
201       12.74   2.01  Female    Yes  Thur   Lunch     2       14.75
202       13.00   2.00  Female    Yes  Thur   Lunch     2       15.00
203       16.40   2.50  Female    Yes  Thur   Lunch     2       18.90
204       20.53   4.00    Male    Yes  Thur   Lunch     4       24.53
205       16.47   3.23  Female    Yes  Thur   Lunch     3       19.70
206       26.59   3.41    Male    Yes   Sat  Dinner     3       30.00
207       38.73   3.00    Male    Yes   Sat  Dinner     4       41.73
208       24.27   2.03    Male    Yes   Sat  Dinner     2       26.30
209       12.76   2.23  Female    Yes   Sat  Dinner     2       14.99
210       30.06   2.00    Male    Yes   Sat  Dinner     3       32.06
211       25.89   5.16    Male    Yes   Sat  Dinner     4       31.05
212       48.33   9.00    Male     No   Sat  Dinner     4       57.33
213       13.27   2.50  Female    Yes   Sat  Dinner     2       15.77
214       28.17   6.50  Female    Yes   Sat  Dinner     3       34.67
215       12.90   1.10  Female    Yes   Sat  Dinner     2       14.00
216       28.15   3.00    Male    Yes   Sat  Dinner     5       31.15
217       11.59   1.50    Male    Yes   Sat  Dinner     2       13.09
218        7.74   1.44    Male    Yes   Sat  Dinner     2        9.18
219       30.14   3.09  Female    Yes   Sat  Dinner     4       33.23
220       12.16   2.20    Male    Yes   Fri   Lunch     2       14.36
221       13.42   3.48  Female    Yes   Fri   Lunch     2       16.90
222        8.58   1.92    Male    Yes   Fri   Lunch     1       10.50
223       15.98   3.00  Female     No   Fri   Lunch     3       18.98
224       13.42   1.58    Male    Yes   Fri   Lunch     2       15.00
225       16.27   2.50  Female    Yes   Fri   Lunch     2       18.77
226       10.09   2.00  Female    Yes   Fri   Lunch     2       12.09
227       20.45   3.00    Male     No   Sat  Dinner     4       23.45
228       13.28   2.72    Male     No   Sat  Dinner     2       16.00
229       22.12   2.88  Female    Yes   Sat  Dinner     2       25.00
230       24.01   2.00    Male    Yes   Sat  Dinner     4       26.01
231       15.69   3.00    Male    Yes   Sat  Dinner     3       18.69
232       11.61   3.39    Male     No   Sat  Dinner     2       15.00
233       10.77   1.47    Male     No   Sat  Dinner     2       12.24
234       15.53   3.00    Male    Yes   Sat  Dinner     2       18.53
235       10.07   1.25    Male     No   Sat  Dinner     2       11.32
236       12.60   1.00    Male    Yes   Sat  Dinner     2       13.60
237       32.83   1.17    Male    Yes   Sat  Dinner     2       34.00
238       35.83   4.67  Female     No   Sat  Dinner     3       40.50
239       29.03   5.92    Male     No   Sat  Dinner     3       34.95
240       27.18   2.00  Female    Yes   Sat  Dinner     2       29.18
241       22.67   2.00    Male    Yes   Sat  Dinner     2       24.67
242       17.82   1.75    Male     No   Sat  Dinner     2       19.57
243       18.78   3.00  Female     No  Thur  Dinner     2       21.78

In [153]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
 7   final_bill  244 non-null    float64
dtypes: float64(3), int64(1), object(4)
memory usage: 15.4+ KB

In [168]:
for cols in df.columns:
  print(cols)

total_bill
tip
sex
smoker
day
time
size
final_bill

In [177]:
df.sample(7)

     total_bill   tip     sex smoker   day    time  size  final_bill
131       20.27  2.83  Female     No  Thur   Lunch     2       23.10
41        17.46  2.54    Male     No   Sun  Dinner     2       20.00
2         21.01  3.50    Male     No   Sun  Dinner     3       24.51
159       16.49  2.00    Male     No   Sun  Dinner     4       18.49
172        7.25  5.15    Male    Yes   Sun  Dinner     2       12.40
243       18.78  3.00  Female     No  Thur  Dinner     2       21.78
223       15.98  3.00  Female     No   Fri   Lunch     3       18.98

## **Data Cleaning**

In [185]:
import numpy as np

print("--- Data Cleaning Examples ---")

# 1. drop() - Drop a column
df_after_drop = df.copy()
df_after_drop = df_after_drop.drop(columns=['size'])
print("\nDataFrame after dropping 'size' column:")
print(df_after_drop.head())

# 2. dropna() and 3. fillna() - Handle missing values
df_with_nans = df.copy()
# Introduce some NaN values for demonstration
df_with_nans.loc[0, 'tip'] = np.nan
df_with_nans.loc[1, 'sex'] = np.nan
df_with_nans.loc[2, 'day'] = np.nan

print("\nDataFrame with introduced NaNs:")
print(df_with_nans.head())

# dropna()
df_after_dropna = df_with_nans.dropna()
print("\nDataFrame after dropna():")
print(df_after_dropna.head())
print(f"Original rows: {len(df_with_nans)}, Rows after dropna: {len(df_after_dropna)}")

# fillna()
# Fill 'tip' with its mean, 'sex' with 'Unknown', and 'day' with 'Other'
df_after_fillna = df_with_nans.fillna({'tip': df_with_nans['tip'].mean(),
                                       'sex': 'Unknown',
                                       'day': 'Other'})
print("\nDataFrame after fillna():")
print(df_after_fillna.head())

# 4. replace() - Replace specific values
df_after_replace = df.copy()
# Replace 'Female' with 'Woman' in the 'sex' column
df_after_replace['sex'] = df_after_replace['sex'].replace('Female', 'Woman')
print("\n'sex' column after replacing 'Female' with 'Woman':")
print(df_after_replace['sex'].value_counts())

# 5. str.lower() - Convert string column to lowercase
df_after_lower = df.copy()
# Convert 'day' column to lowercase
df_after_lower['day'] = df_after_lower['day'].str.lower()
print("\n'day' column after converting to lowercase:")
print(df_after_lower['day'].value_counts())

# 6. astype() - Change data type
df_after_astype = df.copy()
# Convert 'tip' column from float to int
# Note: This will truncate decimal values.
df_after_astype['tip'] = df_after_astype['tip'].astype(int)
print("\nDataFrame head and info after converting 'tip' to int:")
print(df_after_astype.head())
print(df_after_astype.info())

# 7. drop_duplicates() - Remove duplicate rows
# Create a sample DataFrame with duplicates for demonstration
data_with_duplicates = {
    'col1': [1, 2, 1, 3, 2, 4],
    'col2': ['A', 'B', 'A', 'C', 'B', 'D'],
    'col3': [10, 20, 10, 30, 20, 40]
}
df_duplicates_example = pd.DataFrame(data_with_duplicates)
print("\nDataFrame with duplicates for drop_duplicates example:")
print(df_duplicates_example)

df_no_duplicates = df_duplicates_example.drop_duplicates()
print("\nDataFrame after drop_duplicates():")
print(df_no_duplicates)

print("\nDataFrame after drop_duplicates(subset=['col1']):")
df_no_duplicates_subset = df_duplicates_example.drop_duplicates(subset=['col1'])
print(df_no_duplicates_subset)

--- Data Cleaning Examples ---

DataFrame after dropping 'size' column:
   total_bill   tip     sex smoker  day    time  final_bill
0       16.99  1.01  Female     No  Sun  Dinner       18.00
1       10.34  1.66    Male     No  Sun  Dinner       12.00
2       21.01  3.50    Male     No  Sun  Dinner       24.51
3       23.68  3.31    Male     No  Sun  Dinner       26.99
4       24.59  3.61  Female     No  Sun  Dinner       28.20

DataFrame with introduced NaNs:
   total_bill   tip     sex smoker  day    time  size  final_bill
0       16.99   NaN  Female     No  Sun  Dinner     2       18.00
1       10.34  1.66     NaN     No  Sun  Dinner     3       12.00
2       21.01  3.50    Male     No  NaN  Dinner     3       24.51
3       23.68  3.31    Male     No  Sun  Dinner     2       26.99
4       24.59  3.61  Female     No  Sun  Dinner     4       28.20

DataFrame after dropna():
   total_bill   tip     sex smoker  day    time  size  final_bill
3       23.68  3.31    Male     No  Sun  Dinner     2       26.99
4       24.59  3.61  Female     No  Sun  Dinner     4       28.20
5       25.29  4.71    Male     No  Sun  Dinner     4       30.00
6        8.77  2.00    Male     No  Sun  Dinner     2       10.77
7       26.88  3.12    Male     No  Sun  Dinner     4       30.00
Original rows: 244, Rows after dropna: 241

DataFrame after fillna():
   total_bill       tip      sex smoker    day    time  size  final_bill
0       16.99  3.006461   Female     No    Sun  Dinner     2       18.00
1       10.34  1.660000  Unknown     No    Sun  Dinner     3       12.00
2       21.01  3.500000     Male     No  Other  Dinner     3       24.51
3       23.68  3.310000     Male     No    Sun  Dinner     2       26.99
4       24.59  3.610000   Female     No    Sun  Dinner     4       28.20

'sex' column after replacing 'Female' with 'Woman':
sex
Male     157
Woman     87
Name: count, dtype: int64

'day' column after converting to lowercase:
day
sat     87
sun     76
thur    62
fri     19
Name: count, dtype: int64

DataFrame head and info after converting 'tip' to int:
   total_bill  tip     sex smoker  day    time  size  final_bill
0       16.99    1  Female     No  Sun  Dinner     2       18.00
1       10.34    1    Male     No  Sun  Dinner     3       12.00
2       21.01    3    Male     No  Sun  Dinner     3       24.51
3       23.68    3    Male     No  Sun  Dinner     2       26.99
4       24.59    3  Female     No  Sun  Dinner     4       28.20
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    int64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
 7   final_bill  244 non-null    float64
dtypes: float64(2), int64(2), object(4)
memory usage: 15.4+ KB
None

DataFrame with duplicates for drop_duplicates example:
   col1 col2  col3
0     1    A    10
1     2    B    20
2     1    A    10
3     3    C    30
4     2    B    20
5     4    D    40

DataFrame after drop_duplicates():
   col1 col2  col3
0     1    A    10
1     2    B    20
3     3    C    30
5     4    D    40

DataFrame after drop_duplicates(subset=['col1']):
   col1 col2  col3
0     1    A    10
1     2    B    20
3     3    C    30
5     4    D    40